# Generated by Django 5.0.6 on 2024-06-26 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultLogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultlogs',
            name='content',
            field=models.TextField(default='상담 기록이 없습니다', verbose_name='내용'),
        ),
    ]
