# Generated by Django 5.0.6 on 2024-06-26 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultLogs', '0002_alter_consultlogs_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultlogs',
            old_name='doctor',
            new_name='writer',
        ),
    ]
