# Generated by Django 5.0.6 on 2024-06-26 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultLogs', '0003_rename_doctor_consultlogs_writer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultlogs',
            old_name='writer',
            new_name='doctor',
        ),
    ]
