# Generated by Django 4.2.13 on 2024-06-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultLogs', '0004_rename_writer_consultlogs_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultLog',
            fields=[
                ('memoryId', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='작성일')),
                ('doctor', models.CharField(max_length=30, verbose_name='상담사')),
                ('content', models.TextField(default='상담 기록이 없습니다', verbose_name='내용')),
            ],
        ),
        migrations.DeleteModel(
            name='ConsultLogs',
        ),
    ]
