# Generated by Django 4.2.13 on 2024-06-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultLogs', '0005_consultlog_delete_consultlogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultlog',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='작성일'),
        ),
    ]
