# Generated by Django 4.2.13 on 2024-06-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultLogs', '0006_alter_consultlog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultlog',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='작성일'),
        ),
    ]
