# Generated by Django 5.0.6 on 2024-06-26 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='', verbose_name='내용')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
            ],
        ),
    ]
