# Generated by Django 4.2.13 on 2024-06-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_remove_diary_id_diary_diaryid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='date',
            field=models.DateField(verbose_name='작성일'),
        ),
    ]
